apiVersion: connectors.aiops.ibm.com/v1beta1
kind: BundleManifest
metadata:
  name: java-grpc-connector-template
spec:
  prereqs:
    repo: 'https://github.com/tanushs298/cp4waiops-connectors-java-template'
    branch: main
    components:
      - name: deployment
        path: /bundle-artifacts/prereqs
        type: kustomize
  instanced:
    repo: 'https://github.com/tanushs298/cp4waiops-connectors-java-template'
    branch: main
    components:
      - name: connector
        path: /bundle-artifacts/connector
        type: kustomize
